name: child_correction
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/first_boy/first/
    - assets/images/first_boy/second/
    - assets/images/second_boy/first/
    - assets/images/second_boy/second/
    - assets/images/third_boy/
    - assets/images/next/phone/
    - assets/images/next/profession/
    - assets/images/next/transport/
    - assets/images/background/